### PR TITLE
Leaderboard: setup project

### PR DESCRIPTION
**Pull request by ichala**
in this pr I add the following : 
- Install & Setup Webpack, Linters, and npm packages
- Update Readme.MD (more updates will follow later after deployment)
- Write plain HTML markup with minimum styling

### CODE REVIEW

**Review by aimemalaika — CHANGES_REQUESTED** [review]
Hi <STUDENT_MENTION>, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

the-simpsons-homer-simpson

## To Highlight 🎉

- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️
- PR has a good title and summary. ✔️

 ## Required Changes ♻️

- [ ] Kindly make sure that your project structure looks like this
```
app-root-directory
  |- package.json
  |- webpack.config.js
  |- /dist
    |- bundle.js or be main.js
    |- index.html
  |- /src
   |- style.css
    |- index.js
  |- /node_modules (this folder should not appear on github as it is ignored in .gitignore)
```

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ichala** [comment]
@aimemalaika hello sir , thanks for the review but as mentioned [here](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/exercises/exercise_set_up_project_with_webpack.md#html-template) the template HTML file should be in src , and the dist folder is generated later with the build are you saying that i should only add a dist folder ? because I'm totally followed that structure , and its only missing dist folder wich is there but included in .gitignore since it will auto generate when you run `npm run dev`

**Comment by aimemalaika** [comment]
Hello, @ichala yes kindly add the folder dist in the structure as `webpack` put files in the dist folder but does not create the directory for you. and you need `index.html` in src as it is your development folder
Screen Shot 2022-05-09 at 10 05 34

**Review by sja-thedude — CHANGES_REQUESTED** [review]
## Required Changes ♻️

Hi @ichala, This is @sja-thedude your code reviewer.

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

200w

 ## Highlights
✔️ Good job so far

 ## Required Changes ♻️
- [x] Kindly make sure that your app directory is as follows. As suggested by the previous reviewer you have not added a dist folder and files to it. Kindly add it.
```
app-root-directory
  |- package.json
  |- webpack.config.js
  |- /dist
    |- bundle.js or be main.js
    |- index.html
  |- /src
   |- style.css
    |- index.js
  |- /node_modules (this folder should not appear on github as it is ignored in .gitignore)
```

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Meltrust — APPROVED** [review]
Hi @ichala,


## Wow, you did it 🎉
Brilliant
## Thank you for adding the `dist` folder with files, as requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
